// *** LIBS
// ** FONTS
// * CHIVO
import { chivo } from "../libs/fonts";

// *** STYLES
// ** SCSS
// * RESET SCSS
import "@/app/styles/reset.scss";
// * GLOBAL SCSS
import "@/app/styles/global.scss";
// * VARIABLES SCSS
import "@/app/styles/variables.scss";

// *** COMPONENTS
// ** HUGE LOGO
import HugeLogo from "@/components/huge-logo";
// ** HEADER
import Header from "@/components/header";
// ** FOOTER
import Footer from "@/components/footer";

// *** METADATA
// * METADATA
export const metadata = {
  title: "Gumroad Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={chivo.className}>
        <HugeLogo />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
