export const inspirationsData = [
  {
    title: "3D",
    text: "Perfect your craft with the same tools used at Dreamworks and Pixar.",
    href: "/",
    image: "/stickers/categories_sticker_ball.svg",
    backgroundColor: "#23a094",
    tags: [
      { label: "Blender", href: "/" },
      { label: "3D Model", href: "/" },
      { label: "Spark Ar", href: "/" },
    ],
  },
  {
    title: "Audio",
    text: "Open your ears and mind to interviews, meditations, and true crime thrillers.",
    href: "/1",
    image: "/stickers/categories_sticker_audio.svg",
    backgroundColor: "hsla(7.039106145251395, 75.53%, 53.53%, 1.00)",
    tags: [
      { label: "meditation", href: "/" },
      { label: "hypnosis", href: "/" },
      { label: "subliminal messages", href: "/" },
    ],
  },
  {
    title: "Business & Money",
    text: "Learn to earn in an increasingly unpredictable world.",
    href: "/1",
    image: "/stickers/categories_sticker_business.svg",
    backgroundColor: "#23a094",
    tags: [
      { label: "notion template", href: "/" },
      { label: "investing", href: "/" },
      { label: "instagram", href: "/" },
    ],
  },
  {
    title: "Comics & Graphic Novels",
    text: "Sequential art with loads of heart. Welcome to a paradise of panels.",
    href: "/",
    image: "/stickers/categories_sticker_comics.svg",
    backgroundColor: "hsla(60.62499999999999, 88.89%, 57.65%, 1.00)",
    tags: [
      { label: "comic", href: "/" },
      { label: "manga", href: "/" },
      { label: "anime", href: "/" },
    ],
  },
  {
    title: "Design",
    text: "Code, design, and ship your dream product with these technical resources.",
    href: "/",
    image: "/stickers/categories_sticker_design.svg",
    backgroundColor: "hsla(47.294117647058826, 100.00%, 50.00%, 1.00)",
    tags: [
      { label: "textures", href: "/" },
      { label: "mockup", href: "/" },
      { label: "font", href: "/" },
    ],
  },
  {
    title: "Drawing & Painting",
    text: "Tutorials, plugins, and brushes from pro concept artists and illustrators.",
    href: "/",
    image: "/stickers/categories_sticker_drawing.svg",
    backgroundColor: "#90a8ed",
    tags: [
      { label: "procreate", href: "/" },
      { label: "brushes", href: "/" },
      { label: "art", href: "/" },
    ],
  },
  {
    title: "Education",
    text: "Pick up a new skill with courses and guides from world-class pros.",
    href: "/",
    image: "/stickers/categories_sticker_education.svg",
    backgroundColor: "#23a094",
    tags: [
      { label: "Education", href: "/" },
      { label: "certification exams", href: "/" },
      { label: "learning", href: "/" },
    ],
  },
  {
    title: "Fiction Books",
    text: "Short stories, novellas, and epic tomes full of interesting characters and worlds.",
    href: "/",
    image: "/stickers/categories_sticker_education.svg",
    backgroundColor: "#90a8ed",
    tags: [
      { label: "sci-fi", href: "/" },
      { label: "poetry", href: "/" },
      { label: "fiction", href: "/" },
    ],
  },
  {
    title: "Films",
    text: "Have a movie night with some of the best stories to hit the small screen.",
    href: "/",
    image: "/stickers/categories_sticker_film.svg",
    backgroundColor: "hsla(7.039106145251395, 75.53%, 53.53%, 1.00)",
    tags: [
      { label: "after effects", href: "/" },
      { label: "vj loops", href: "/" },
      { label: "luts", href: "/" },
    ],
  },
  {
    title: "Fitness & Health",
    text: "Whether you’re looking to shed or shred, here are coaches to pump you up.",
    href: "/",
    image: "/stickers/categories_sticker_fitness.svg",
    backgroundColor: "hsla(47.294117647058826, 100.00%, 50.00%, 1.00)",
    tags: [
      { label: "fitness", href: "/" },
      { label: "workout program", href: "/" },
      { label: "yoga", href: "/" },
    ],
  },
  {
    title: "Gaming",
    text: "Explore new worlds from the world’s most creative indie developers.",
    href: "/",
    image: "/stickers/categories_sticker_gaming.svg",
    backgroundColor: "hsla(7.039106145251395, 75.53%, 53.53%, 1.00)",
    tags: [
      { label: "vrchat", href: "/" },
      { label: "avatar", href: "/" },
      { label: "assets", href: "/" },
    ],
  },
  {
    title: "Music & Sound Design",
    text: "Tracks, beats, and loops from the best musicians and engineers in the biz.",
    href: "/",
    image: "/stickers/categories_sticker_music.svg",
    backgroundColor: "hsla(60.62499999999999, 88.89%, 57.65%, 1.00)",
    tags: [
      { label: "ableton", href: "/" },
      { label: "sample pack", href: "/" },
      { label: "sheet music", href: "/" },
    ],
  },
  {
    title: "Photography",
    text: "Get snapping with pro presets, stock imagery, and digi darkroom needs.",
    href: "/",
    image: "/stickers/categories_sticker_photo.svg",
    backgroundColor: "#23a094",
    tags: [
      { label: "reference photos", href: "/" },
      { label: "stock photos", href: "/" },
      { label: "photobash", href: "/" },
    ],
  },
  {
    title: "Recorded Music",
    text: "Tracks and albums from the best musicians and artists in the biz.",
    href: "/",
    image: "/stickers/categories_sticker_music.svg",
    backgroundColor: "hsla(60.62499999999999, 88.89%, 57.65%, 1.00)",
    tags: [
      { label: "singles", href: "/" },
      { label: "jazz", href: "/" },
      { label: "instrumental music", href: "/" },
    ],
  },
  {
    title: "Self Improvement",
    text: "Move your body and your audience with guides, videos, and more.",
    href: "/",
    image: "/stickers/categories_sticker_self.svg",
    backgroundColor: "hsla(7.039106145251395, 75.53%, 53.53%, 1.00)",
    tags: [
      { label: "coloring page", href: "/" },
      { label: "printable", href: "/" },
      { label: "productivity", href: "/" },
    ],
  },
  {
    title: "Software Development",
    text: "Learn to code and tools to help you code more productively.",
    href: "/",
    image: "/stickers/categories_sticker_software.svg",
    backgroundColor: "hsla(47.294117647058826, 100.00%, 50.00%, 1.00)",
    tags: [
      { label: "programming", href: "/" },
      { label: "windows", href: "/" },
      { label: "theme", href: "/" },
    ],
  },
  {
    title: "Writing & Publishing",
    text: "Fill your brain with words and wisdom from creative authors and storytellers.",
    href: "/",
    image: "/stickers/categories_sticker_writing.svg",
    backgroundColor: "#90a8ed",
    tags: [
      { label: "kdp interior", href: "/" },
      { label: "ebook", href: "/" },
      { label: "low content books", href: "/" },
    ],
  },
];
